In [43]:
import pandas as pd
import scipy.stats as stats
import numpy as np
from dython.nominal import theils_u

In [4]:
df_ban_heroes = pd.read_csv('../data/ban_heroes.csv')
df_pick_heroes = pd.read_csv('../data/pick_heroes.csv')

df_draft_heroes = df_ban_heroes.merge(df_pick_heroes, on='game_id')
df_draft_heroes = df_draft_heroes.rename(columns={
  'team_1_ban_1': 'step_1', 'team_2_ban_1': 'step_2', 'team_1_ban_2': 'step_3', 'team_2_ban_2': 'step_4',
  'team_1_ban_3': 'step_5', 'team_2_ban_3': 'step_6', 'team_1_pick_1': 'step_7', 'team_2_pick_1': 'step_8',
  'team_2_pick_2': 'step_9', 'team_1_pick_2': 'step_10', 'team_1_pick_3': 'step_11', 'team_2_pick_3': 'step_12',
  'team_2_ban_4': 'step_13', 'team_1_ban_4': 'step_14', 'team_2_ban_5': 'step_15', 'team_1_ban_5': 'step_16',
  'team_2_pick_4': 'step_17', 'team_1_pick_4': 'step_18', 'team_1_pick_5': 'step_19', 'team_2_pick_5': 'step_20'
})
df_draft_heroes = df_draft_heroes[['game_id', 'step_1', 'step_2', 'step_3', 'step_4', 'step_5', 'step_6', 'step_7', 'step_8', 'step_9', 'step_10',
                                   'step_11', 'step_12', 'step_13', 'step_14','step_15', 'step_16', 'step_17', 'step_18', 'step_19', 'step_20']]
df_draft_heroes.head()

,game_id,step_1,step_2,step_3,step_4,step_5,step_6,step_7,step_8,step_9,...,step_11,step_12,step_13,step_14,step_15,step_16,step_17,step_18,step_19,step_20
0,1,fanny,chip,zhask,ling,hayabusa,zhuxin,luo yi,valentina,roger,...,moskov,arlott,x.borg,joy,hylos,nolan,chou,julian,minotaur,harith
1,2,zhuxin,chip,khufra,ling,moskov,fanny,valentina,roger,edith,...,harith,arlott,terizla,hayabusa,hylos,luo yi,vexana,minotaur,thamuz,joy
2,3,terizla,chip,zhuxin,zhask,harith,ling,valentina,khufra,moskov,...,claude,vexana,minotaur,hayabusa,carmilla,alpha,ruby,julian,hylos,nolan
3,4,terizla,chip,zhuxin,ling,harith,edith,valentina,roger,zhask,...,moskov,hylos,fanny,alpha,joy,hayabusa,guinevere,julian,x.borg,claude
4,5,zhuxin,chip,terizla,ling,zhask,edith,valentina,roger,harith,...,moskov,x.borg,fanny,luo yi,hayabusa,minotaur,guinevere,julian,paquito,novaria

In [5]:
df_game_information = pd.read_csv('../data/game_information.csv')
df = df_game_information.merge(df_draft_heroes, on='game_id')
df.head()

,game_id,date,team_1,team_2,game_number,team_winner,patch_version,step_1,step_2,step_3,...,step_11,step_12,step_13,step_14,step_15,step_16,step_17,step_18,step_19,step_20
0,1,9-Aug-2024,tlid,fnoc,1,fnoc,1.9.06,fanny,chip,zhask,...,moskov,arlott,x.borg,joy,hylos,nolan,chou,julian,minotaur,harith
1,2,9-Aug-2024,fnoc,tlid,2,fnoc,1.9.06,zhuxin,chip,khufra,...,harith,arlott,terizla,hayabusa,hylos,luo yi,vexana,minotaur,thamuz,joy
2,3,9-Aug-2024,dewa,evos,1,dewa,1.9.06,terizla,chip,zhuxin,...,claude,vexana,minotaur,hayabusa,carmilla,alpha,ruby,julian,hylos,nolan
3,4,9-Aug-2024,dewa,evos,2,evos,1.9.06,terizla,chip,zhuxin,...,moskov,hylos,fanny,alpha,joy,hayabusa,guinevere,julian,x.borg,claude
4,5,9-Aug-2024,dewa,evos,3,dewa,1.9.06,zhuxin,chip,terizla,...,moskov,x.borg,fanny,luo yi,hayabusa,minotaur,guinevere,julian,paquito,novaria

In [20]:
def cramers_v(x, y):
  confusion_matrix = pd.crosstab(x, y)
  chi2 = stats.chi2_contingency(confusion_matrix)[0]
  n = confusion_matrix.sum().sum()
  phi2 = chi2 / n
  r, k = confusion_matrix.shape
  return np.sqrt(phi2 / min(k - 1, r - 1))

In [42]:
v = cramers_v(df['patch_version'], df['step_8'])
print("cramer's v:", v)

cramer's v: 0.7775789159450107

In [19]:
contigency_table = pd.crosstab(df['patch_version'], df['step_8'])
chi2, p, dof, ex = stats.chi2_contingency(contigency_table)

print('chi2:', chi2)
print('p-value:', p)

chi2: 127.57671278018802
p-value: 6.922794478412164e-12

In [78]:
u = theils_u(df['patch_version'], df['step_20'])
print("Theil's u:", u)

Theil's u: 0.27796451166587977